In [1]:
import aeolis
import numpy as np

In [23]:
s = np.arange(10,dtype=np.float)-5
print s

a = aeolis.bed.normalize(s[1:6],ref=s[0:5])
#b = aeolis.bed.normalize(s)

print a.sum()
#print b

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
[-5. -4. -3. -2. -1.]
2.71666666667


In [31]:
np.abs(s)

array([ 5.,  4.,  3.,  2.,  1.,  0.,  1.,  2.,  3.,  4.])